# Use postgres/example user/password credentials
version: '3.8'

services:

  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db/seed:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: user@domain.com
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

  postgres-pgtap:
    build:
      context: .
      dockerfile: Dockerfile