export enum Permission {
    BOARD_TREE_CREATE = 'BOARD_TREE_CREATE',
    BOARD_TREE_DELETE = 'BOARD_TREE_DELETE',
    BOARD_NODE_CREATE = 'BOARD_NODE_CREATE',
    BOARD_NODE_READ = 'BOARD_NODE_READ',
    BOARD_NODE_UPDATE = 'BOARD_NODE_UPDATE',
    BOARD_NODE_DELETE = 'BOARD_NODE_DELETE',
    BOARD_NODE_CREATE_TASK = 'BOARD_NODE_CREATE_TASK',
    BOARD_NODE_SUBMIT_TASK = 'BOARD_NODE_SUBMIT_TASK',
    FILESTORAGE_CREATE = 'FILESTORAGE_CREATE',
    FILESTORAGE_READ = 'FILESTORAGE_READ',
    FILESTORAGE_UPDATE = 'FILESTORAGE_UPDATE',
    FILESTORAGE_DELETE = 'FILESTORAGE_DELETE',
}
